baseURL = 'http://example.org/'
languageCode = 'en-us'
title = 'Mi Sitio'
theme = "tale"

[menu]
  [[menu.main]]
    identifier = "contacto"
    name = "contacto"
    title = "contacto"
    url = "/contacto/"
    weight = 0
  [[menu.main]]
    identifier = "post"
    name = "Post"
    title = "Post"
    url = "/post/"
    weight = 0
